# Is This Tweet Positive?

Bag of Words - https://en.wikipedia.org/wiki/Bag-of-words_model

**Credit:** http://ravikiranj.net/posts/2012/code/how-build-twitter-sentiment-analyzer/

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
vectorizer = CountVectorizer(stop_words='english')

In [3]:
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [4]:
X_train = [
    'Hey Cici sweetheart! Just wanted to let u know I luv u! OH! and will the mixtape drop soon? FANTASY RIDE MAY 5TH!!!!',
    'I heard about that contest! Congrats girl!!',
    'UNC!!! NCAA Champs!! Franklin St.: I WAS THERE!! WILD AND CRAZY!!!!!! Nothing like it...EVER http://tinyurl.com/49955t3',
    'Do you Share More #jokes #quotes #music #photos or #news #articles on #Facebook or #Twitter?',
    'Good night #Twitter and #TheLegionoftheFallen. 5:45am cimes awfully early!',
    'I just finished a 2.66 mi run with a pace of 11\'14"/mi with Nike+ GPS. #nikeplus #makeitcount',
    'Disappointing day. Attended a car boot sale to raise some funds for the sanctuary, made a total of 88p after the entry fee - sigh',
    'no more taking Irish car bombs with strange Australian women who can drink like rockstars...my head hurts.',
    'Just had some bloodwork done. My arm hurts'
]

y_train = [
    'positive',
    'positive',
    'positive',
    'neutral',
    'neutral',
    'neutral',
    'negative',
    'negative',
    'negative'
]

In [5]:
X_train = vectorizer.fit_transform(X_train)

In [6]:
vectorizer.get_feature_names()

['11',
 '14',
 '45am',
 '49955t3',
 '5th',
 '66',
 '88p',
 'arm',
 'articles',
 'attended',
 'australian',
 'awfully',
 'bloodwork',
 'bombs',
 'boot',
 'car',
 'champs',
 'cici',
 'cimes',
 'com',
 'congrats',
 'contest',
 'crazy',
 'day',
 'disappointing',
 'drink',
 'drop',
 'early',
 'entry',
 'facebook',
 'fantasy',
 'fee',
 'finished',
 'franklin',
 'funds',
 'girl',
 'good',
 'gps',
 'head',
 'heard',
 'hey',
 'http',
 'hurts',
 'irish',
 'jokes',
 'just',
 'know',
 'let',
 'like',
 'luv',
 'makeitcount',
 'mi',
 'mixtape',
 'music',
 'ncaa',
 'news',
 'night',
 'nike',
 'nikeplus',
 'oh',
 'pace',
 'photos',
 'quotes',
 'raise',
 'ride',
 'rockstars',
 'run',
 'sale',
 'sanctuary',
 'share',
 'sigh',
 'soon',
 'st',
 'strange',
 'sweetheart',
 'taking',
 'thelegionofthefallen',
 'tinyurl',
 'total',
 'twitter',
 'unc',
 'wanted',
 'wild',
 'women']

In [7]:
[vectorizer.get_feature_names()[8], vectorizer.get_feature_names()[9], vectorizer.get_feature_names()[10]]

['articles', 'attended', 'australian']

In [8]:
X_train

<9x84 sparse matrix of type '<class 'numpy.int64'>'
	with 90 stored elements in Compressed Sparse Row format>

In [9]:
type(X_train)

scipy.sparse.csr.csr_matrix

In [10]:
X_train.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
vectorizer.inverse_transform(X_train)

In [11]:
X_test = ['This woman is my sweetheart']
X_test = vectorizer.transform(X_test)
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Predicting Sentiment from Tweet

In [16]:
X_test = ['Congrats @ravikiranj, i heard you wrote a new tech post on sentiment analysis']

In [17]:
X_test = vectorizer.transform(X_test)

In [18]:
X_test

<1x84 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [19]:
[X_test.toarray()[0][8], X_test.toarray()[0][9], X_test.toarray()[0][10]]

[0, 0, 0]

In [20]:
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
vectorizer.inverse_transform(X_test)

[array(['congrats', 'heard'], dtype='<U20')]

In [22]:
# import
from sklearn import naive_bayes

# instantiate
clf = naive_bayes.MultinomialNB()

# fit
clf.fit(X_train, y_train)

# predict
clf.predict(X_test)

array(['positive'], dtype='<U8')

Try another tweet!

In [23]:
X_test = ['I am very bored today.']
X_test = vectorizer.transform(X_test)

In [24]:
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
clf.predict(X_test)

array(['negative'], dtype='<U8')

In [26]:
X_test = ['Good morning!']
X_test = vectorizer.transform(X_test)
clf.predict(X_test)

array(['neutral'], dtype='<U8')

In [27]:
X_test = ['I luv you']
X_test = vectorizer.transform(X_test)
clf.predict(X_test)

array(['positive'], dtype='<U8')